drop table if exists rosters;

-- rosters holds the information for each roster by week
create table rosters (
    roster_id         VARCHAR NOT NULL,
    league_id         VARCHAR NOT NULL,
    week              INTEGER,
    matchup_id        VARCHAR,
    starter_1         VARCHAR,
    starter_1_points  VARCHAR,
    starter_2         VARCHAR,
    starter_2_points  VARCHAR,
    starter_3         VARCHAR,
    starter_3_points  VARCHAR,
    starter_4         VARCHAR,
    starter_4_points  VARCHAR,
    starter_5         VARCHAR,
    starter_5_points  VARCHAR,
    starter_6         VARCHAR,
    starter_6_points  VARCHAR,
    starter_7         VARCHAR,
    starter_7_points  VARCHAR,
    starter_8         VARCHAR,
    starter_8_points  VARCHAR,
    starter_9         VARCHAR,
    starter_9_points  VARCHAR,
    starter_10        VARCHAR,
    starter_10_points VARCHAR,
    bench_1         VARCHAR,
    bench_1_points  VARCHAR,
    bench_2         VARCHAR,
    bench_2_points  VARCHAR,
    bench_3         VARCHAR,
    bench_3_points  VARCHAR,
    bench_4         VARCHAR,
    bench_4_points  VARCHAR,
    bench_5         VARCHAR,
    bench_5_points  VARCHAR,
    bench_6         VARCHAR,
    bench_6_points  VARCHAR,
    bench_7         VARCHAR,
    bench_7_points  VARCHAR,
    bench_8         VARCHAR,
    bench_8_points  VARCHAR,
    bench_9         VARCHAR,
    bench_9_points  VARCHAR,
    bench_10        VARCHAR,
    bench_10_points VARCHAR,
    bench_11         VARCHAR,
    bench_11_points  VARCHAR,
    bench_12         VARCHAR,
    bench_12_points  VARCHAR,
    bench_13         VARCHAR,
    bench_13_points  VARCHAR,
    bench_14         VARCHAR,
    bench_14_points  VARCHAR,
    bench_15         VARCHAR,
    bench_15_points  VARCHAR,
    bench_16         VARCHAR,
    bench_16_points  VARCHAR,
    bench_17         VARCHAR,
    bench_17_points  VARCHAR,
    bench_18         VARCHAR,
    bench_18_points  VARCHAR,
    bench_19         VARCHAR,
    bench_19_points  VARCHAR,
    bench_20        VARCHAR,
    bench_20_points VARCHAR,
    bench_21        VARCHAR,
    bench_21_points VARCHAR,
    bench_22         VARCHAR,
    bench_22_points  VARCHAR,
    bench_23         VARCHAR,
    bench_23_points  VARCHAR,
    bench_24         VARCHAR,
    bench_24_points  VARCHAR,
    bench_25         VARCHAR,
    bench_25_points  VARCHAR,
    primary key (roster_id, league_id, week)
);
